version: '2'
services:
    server1:
        build: server
        container_name: server1

    server2:
        build: server
        container_name: server2

    client:
        build: client
        container_name: client
        external_links:
            - server1:server1
            - server2:server2
        environment:
            - DEPENDS_ON=server1 server2
